#!/usr/bin/env bash
#
#   - Creates the file /var/run/myscript.pid containing its PID
#   - Displays To infinity and beyond indefinitely
#   - Displays I hate the kill command when receiving a SIGTERM signal
#   - Displays Y U no love me?! when receiving a SIGINT signal
#   - Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

sudo touch /var/run/holbertonscript.pid
echo $$ >> sudo /var/run/holbertonscript.pid
trap "exit_sigterm" SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap "exit_sigquit" SIGQUIT
exit_sigterm()
{
    echo "I hate the kill command"
    sudo rm /var/run/holbertonscript.pid
    exit 1
}
exit_sigquit()
{
    sudo rm /var/run/holbertonscript.pid
    exit 1
}
while ((1))
do
    echo "To infinity and beyond"
    sleep 2
done
